### ISSUE TITLE
Epic: Landing Page

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#1480]
## Description of the enhancement

* Multiple vocabulary layout [static example](https://github.com/NatLibFi/Skosmos/blob/skosmos-3-html/frontpage.html)
* Single vocabulaty layout [static example](https://github.com/NatLibFi/Skosmos/blob/skosmos-3-html/frontpage-one-vocab.html)

- [x] Multiple vocabulary layout implemented
- [ ] Single vocabulary layout implemented
- [ ] Customizable service logo ("Skosmos" by default)
- [x] Main heading is "Vocabularies" / "Sanastot"
- [x] Vocabularies grouped by category; category headings follow visual spec (size, color, padding/margin)
- [x] Vocabularies shown; vocabulary names follow visual spec (size, color, underline offset, underline color, padding/margin)
- [x] Equal length columns (aligned at both top and bottom)
- [x] Footer implemented and follows visual spec
- [x] Keyboard navigation works
- [x] Responsive layout
- [ ] The background should have a line motif
- [x] The background colour should follow the spec
- [x] The space between the columns follows the spec
