### ISSUE TITLE
Implement basic functionality of groups view using Vue

### ISSUE THREAD

**Issue by UnniKohonen** [NatLibFi/Skosmos#1710]
## Description of the enhancement

Implement basic functionality of the groups view in sidebar using Vue. Part of #1704.

## What new functionalities would the enhancement make possible?

Enable viewing and navigating the groups hierarchy in the UI.

## Task list

  - [ ] Loading and building correct tree structure when group hierarchy is not expanded (on vocab home)
  - [ ] Loading and building correct tree structure when group hierarchy is expanded (on group page)
  - [ ] Loading new groups/concepts into group hierarchy
  - [ ] Displaying group hierarchy in UI
