### ISSUE TITLE
Groups view layout and styling

### ISSUE THREAD

**Issue by UnniKohonen** [NatLibFi/Skosmos#1727]
## Description of the enhancement

Implementing correct layout and adding correct styling in the groups view in Skosmos 3. Part of #1704.

## What new functionalities would the enhancement make possible?

Correctly visually displaying the groups view.

## Task list

- [ ]  Correct sidebar sizing
  - [ ]  Correct height and width on load
  - [ ]  Correct width on window resize
- [ ]  Icons and lines
- [x]  Highlighting selected group/concept
- [ ]  Colors, text weight, etc.
- [x]  Loading spinners
